name: Compiling Minecraft Mod (Updated)
description: Very simple action to compile your Minecraft mod
branding:
  icon: archive
  color: white

inputs:
  java-version:
    description: "Java version to use (e.g., 17, 21, 24)"
    required: false
    default: "21"

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "adopt"

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew build
      shell: bash
